name: Build Xamarin.Android app

on: [push]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4


    - name: Install dependencies
      run: nuget restore ../Diary.sln

    - name: Build
      run: msbuild Diary/Diary.Android/Diary.Android.csproj /t:PackageForAndroid /p:Configuration=Debug
